### Create a sale report
POST http://localhost:3000/reports
content-type: application/json

{
    "make": "ford",
    "model": "mustang",
    "year": 2023,
    "lng": 0,
    "lat": 0,
    "mileage": 0,
    "price": 60000
}

### Approve an report
PATCH http://localhost:3000/reports/10
content-type: application/json

{
    "approved": true
}

### Get an estimate for a vehicle
GET http://localhost:3000/reports?make=ford&model=mustang&year=2023&lng=0&lat=0&mileage=87000